version: '3'

services:

  main-db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: zxcfgvwertqwfsdzfwase
      MYSQL_DATABASE: webshop
      MYSQL_USER: app
      MYSQL_PASSWORD: asdfqwerqwerhjijml
    volumes:
      - db_volume:/var/lib/mysql

  redis:
    image: "redis:alpine"
    command: redis-server --requirepass sOmE_sEcUrE_pAsS --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_volume:/data
    environment:
      - REDIS_REPLICATION_MODE=master

  php-fpm:
    build:
      context: ./docker/php-fpm
    depends_on:
      - main-db
    environment:
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=mysql://app:asdfqwerqwerhjijml@main-db:3306/webshop?serverVersion=8.0
      - XDEBUG_CONFIG=remote_host=172.17.0.1 remote_enable=1 remote_autostart=off remote_port=9008
      - REDIS_PASS=sOmE_sEcUrE_pAsS
    volumes:
      - .:/var/www
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini

  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"

volumes:
  db_volume:
  redis_volume:
